spring:
  main:
    web-application-type: NONE
generator:
  generert:
    modul-mappe: melosys-internt-kodeverk
    kildekode-mappe: ${generator.generert.modul-mappe}/src/main/java
    kodeverk-mappe: ${generator.generert.kildekode-mappe}/no/nav/melosys/domain/kodeverk
  ressurser:
    template-mappe: /templates
    standard-enum-filer:
      - Kodeverk
      - Bestemmelse
      - LovvalgBestemmelse
    kodeverk-template: Kodeverk.ftlh
#  versjon-fil: melosys-kodeverk-generator/src/test/resources/dist/semver.txt
#  kodeverk-Yaml: melosys-kodeverk-generator/src/test/resources/dist/kodemap.yml
  folketrygdenBestemmelse-enum-filer:
    - Folketrygdloven_kap2_bestemmelser
  lovvalgBestemmelse-enum-filer:
    - Lovvalgbestemmelser_883_2004
    - Lovvalgbestemmelser_987_2009
    - Tilleggsbestemmelser_883_2004
    - Overgangsregelbestemmelser
    - Lovvalgsbestemmelser_trygdeavtale_au
    - Lovvalgsbestemmelser_trygdeavtale_ba
    - Lovvalgsbestemmelser_trygdeavtale_ca
    - Lovvalgsbestemmelser_trygdeavtale_ca_qc
    - Lovvalgsbestemmelser_trygdeavtale_ch
    - Lovvalgsbestemmelser_trygdeavtale_cl
    - Lovvalgsbestemmelser_trygdeavtale_fr
    - Lovvalgsbestemmelser_trygdeavtale_gb
    - Lovvalgsbestemmelser_trygdeavtale_gr
    - Lovvalgsbestemmelser_trygdeavtale_hr
    - Lovvalgsbestemmelser_trygdeavtale_il
    - Lovvalgsbestemmelser_trygdeavtale_in
    - Lovvalgsbestemmelser_trygdeavtale_it
    - Lovvalgsbestemmelser_trygdeavtale_me
    - Lovvalgsbestemmelser_trygdeavtale_pt
    - Lovvalgsbestemmelser_trygdeavtale_rs
    - Lovvalgsbestemmelser_trygdeavtale_si
    - Lovvalgsbestemmelser_trygdeavtale_tr
    - Lovvalgsbestemmelser_trygdeavtale_us
    - Tilleggsbestemmelser_trygdeavtale_ca
    - Tilleggsbestemmelser_trygdeavtale_cl
    - Lovvalgbestemmelser_konv_efta_storbritannia
    - Tilleggsbestemmelser_konv_efta_storbritannia
  pakke-navn: no.nav.melosys.domain.kodeverk

