on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  bygge_frontend:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3.5.0
        with:
          node-version: '12'
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: v1-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            v1-yarn-
      - run: yarn install
      - run: yarn test
      - run: yarn build
      - uses: actions/upload-artifact@v1
        with:
          name: melosys-kodeverk-dist
          path: dist
      - uses: actions/upload-artifact@v1
        with:
          name: melosys-kodeverk-lib
          path: lib

  bygge_backend:
    needs: bygge_frontend
    runs-on: ubuntu-latest
    steps:
      # GitHub Actions tillater kun filer under workspace i cache-nøkler
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: v1-m2build-${{ hashFiles('app.jar') }}
          restore-keys: |
            v1-m2build-
      - uses: actions/download-artifact@v1
        with:
          name: melosys-kodeverk-dist
          path: melosys-kodeverk/dist
      - name: Bygg melosys-kodeverk-java
        working-directory: melosys-kodeverk-java
        run: |
          mvn clean install
      - name: Generere kildekode for Java-kodeverk
        working-directory: melosys-kodeverk-java
        run: |
          set -e
          java -jar melosys-kodeverk-generator/target/melosys-kodeverk-generator-1.jar ../melosys-kodeverk/dist/kodemap.yml
      - name: Bygge Java-kodeverk
        working-directory: melosys-kodeverk-java/melosys-internt-kodeverk
        run: mvn clean install -B -V
      - uses: actions/upload-artifact@v1
        with:
          name: melosys-kodeverk-java
          path: melosys-kodeverk-java/melosys-internt-kodeverk

  lage_versjoner:
    needs: bygge_backend
    runs-on: ubuntu-latest
    outputs:
      frontend_versjon: ${{ steps.versjoner.outputs.frontend }}
      backend_versjon: ${{ steps.versjoner.outputs.backend }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3.5.0
        with:
          node-version: '12'
      - name: Øk versjon
        if: github.ref == 'refs/heads/master'
        run: |
          git config --global user.email "actions-melosys@nav.no"
          git config --global user.name "Actions"
          COMMIT_MESSAGE=`git log -1 --pretty=%B`
          npm version patch -m "%s, $COMMIT_MESSAGE, [skip ci]"
      - name: Push versjon
        if: github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TEMP_GITHUB_TOKEN }}
      - name: Hent short sha1
        if: github.ref != 'refs/heads/master'
        id: parse_commit
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      - id: versjoner
        run: |
          SEMVER=$(jq -r .version package.json)
          if [ ${IS_MASTER} == true ]; then
            echo "::set-output name=frontend::${SEMVER}"
            echo "::set-output name=backend::${SEMVER}"
          else
            # GPR støtter ikke mutable artifacts (snapshot/beta)
            echo "::set-output name=frontend::${SEMVER}-beta.${SHORT_SHA}"
            echo "::set-output name=backend::${SEMVER}-${SHORT_SHA}"
          fi
        env:
          IS_MASTER: ${{ github.ref == 'refs/heads/master' }}
          PR_NUMBER: ${{ github.event.number }}
          SHORT_SHA: ${{ steps.parse_commit.outputs.short_sha }}

  release_frontend:
    needs: lage_versjoner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v1
        with:
          name: melosys-kodeverk-lib
          path: lib
      - uses: actions/setup-node@v3.5.0
        with:
          node-version: '12'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@navikt'
      - name: Publisere til GitHub package registry
        run: |
          # FIXME: Burde ikke være nødvendig, men registry-url og scope fra setup-node, ser ikke ut til å bli plukka opp
          npm config set registry https://npm.pkg.github.com/@navikt

          if [ ${IS_MASTER} == true ]; then
            # Setter versjon eksplisitt for å slippe å trigge på taggen fra forrige jobb
            npm --no-git-tag-version version ${FRONTEND_VERSION}
            npm publish --access public
          else
            npm --no-git-tag-version version ${FRONTEND_VERSION} --allow-same-version
            npm publish --tag beta
          fi
        env:
          IS_MASTER: ${{ github.ref == 'refs/heads/master' }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FRONTEND_VERSION: ${{ needs.lage_versjoner.outputs.frontend_versjon }}

  release_backend:
    needs: lage_versjoner
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - uses: actions/download-artifact@v1
        with:
          name: melosys-kodeverk-java
          path: .
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: v1-m2release-${{ hashFiles('melosys-internt-kodeverk/pom.xml') }}
          restore-keys: |
            v1-m2release-
      - name: Publisere til GitHub package registry
        run: |
          mvn dependency:resolve --settings settings.xml
          mvn dependency:resolve-plugins --settings settings.xml
          mvn versions:set -DnewVersion=${BACKEND_VERSION}
          mvn -B deploy -Prelease -DskipTests=true --settings settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BACKEND_VERSION: ${{ needs.lage_versjoner.outputs.backend_versjon }}
