name: Dependabot Automerge

on:
  schedule:
    - cron: '0 4 * * 1-5'
  workflow_dispatch:

permissions: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: read
      statuses: read
    steps:
      - uses: actions/create-github-app-token@v3.2.0
        id: app-token
        with:
          client-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Automerge Dependabot PRs
        uses: navikt/automerge-dependabot@v1.5.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          blackout-periods: 'Sat,Sun,Dec 24-Jan 2'
          semver-filter: 'patch,minor'
          merge-method: 'squash'
